# Generated by Django 4.2.7 on 2024-01-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='kike_new',
            field=models.BooleanField(default=False),
        ),
    ]
