# Generated by Django 4.2.7 on 2024-01-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_kike_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='kike_new',
        ),
    ]
