# Generated by Django 4.2.7 on 2024-01-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_band_kike_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='locale',
            field=models.CharField(default='', max_length=23),
        ),
    ]
