# Generated by Django 4.2.7 on 2024-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('RB', 'Rythm And Blues'), ('RK', 'Rock'), ('GP', 'Gospel')], max_length=5),
        ),
    ]
